apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-app-san-pvc
  namespace: demo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard-san
