# based on https://banzaicloud.com/blog/pod-security-policy/
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-psp
  namespace: demo-app
rules:
- apiGroups:
  - policy
  resourceNames:
  - unrestricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privileged-psp-binding
  namespace: demo-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: privileged-psp
subjects:
  - kind: ServiceAccount
    name: default
    namespace: demo-app
