apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-secret
type: Opaque
stringData:
  username: vsadmin
  password: netapp123
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-san-secret
stringData:
  username: vsadmin
  password: netapp123
  chapTargetInitiatorSecret: netapp123
  chapTargetUsername: k8sworker
  chapInitiatorSecret: netapp456
  chapUsername: trident
type: Opaque
